// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamNET.Models;

namespace TeamNET.Migrations
{
    [DbContext(typeof(OJTDbContext))]
    partial class OJTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "291cbc7f-1345-45df-b8c2-96111d13ad60",
                            ConcurrencyStamp = "7f1afc1e-eb95-4455-b6b9-301e5fc46ac4",
                            Name = "System Admin",
                            NormalizedName = "SYSTEM ADMIN"
                        },
                        new
                        {
                            Id = "947b70ee-4b80-4299-a3e4-b03df15501c1",
                            ConcurrencyStamp = "ead43932-327f-411e-9313-bc399e503d22",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "e346ef58-52dd-485d-92a3-25a64144bdfa",
                            ConcurrencyStamp = "b5591e23-dda4-4788-a3b6-1fb3b1f07d04",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "f7e3b187-7743-4c11-a73f-398fe418acd1",
                            ConcurrencyStamp = "5836f016-3405-4b44-b692-44cf861babb0",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "a35c7eb1-a14a-4eed-9ec2-467127acedc1",
                            ConcurrencyStamp = "cd64acc6-d3ee-42f5-96a1-0518e9e94509",
                            Name = "Guardian",
                            NormalizedName = "GUARDIAN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "06b12f97-bb16-434a-9982-e3d3dc1c5145",
                            RoleId = "291cbc7f-1345-45df-b8c2-96111d13ad60"
                        },
                        new
                        {
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c",
                            RoleId = "e346ef58-52dd-485d-92a3-25a64144bdfa"
                        },
                        new
                        {
                            UserId = "1efe96d9-6618-4269-a6e3-ae1e3d3eecc4",
                            RoleId = "e346ef58-52dd-485d-92a3-25a64144bdfa"
                        },
                        new
                        {
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba",
                            RoleId = "f7e3b187-7743-4c11-a73f-398fe418acd1"
                        },
                        new
                        {
                            UserId = "29a908b8-3ac4-45ea-a8a1-1cf9946079c7",
                            RoleId = "f7e3b187-7743-4c11-a73f-398fe418acd1"
                        },
                        new
                        {
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8",
                            RoleId = "947b70ee-4b80-4299-a3e4-b03df15501c1"
                        },
                        new
                        {
                            UserId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c",
                            RoleId = "947b70ee-4b80-4299-a3e4-b03df15501c1"
                        },
                        new
                        {
                            UserId = "3c592e96-f3ad-4e8b-9cbe-afb7ea745362",
                            RoleId = "947b70ee-4b80-4299-a3e4-b03df15501c1"
                        },
                        new
                        {
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c",
                            RoleId = "a35c7eb1-a14a-4eed-9ec2-467127acedc1"
                        },
                        new
                        {
                            UserId = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5",
                            RoleId = "a35c7eb1-a14a-4eed-9ec2-467127acedc1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TeamNET.Models.Entity.Ability", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AbilityId");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            AbilityId = 1,
                            AbilityName = "Tính tự lập",
                            Color = "#3a2d38"
                        },
                        new
                        {
                            AbilityId = 2,
                            AbilityName = "Khả năng làm việc",
                            Color = "#1d545b"
                        },
                        new
                        {
                            AbilityId = 3,
                            AbilityName = "Khả năng thực hành",
                            Color = "#f4d8cd"
                        },
                        new
                        {
                            AbilityId = 4,
                            AbilityName = "Khả năng giải quyết vấn đề",
                            Color = "#f78c3a"
                        },
                        new
                        {
                            AbilityId = 5,
                            AbilityName = "Khả năng lập kế hoạch",
                            Color = "#d62f0a"
                        },
                        new
                        {
                            AbilityId = 6,
                            AbilityName = "Khả năng sáng tạo",
                            Color = "#efa101"
                        },
                        new
                        {
                            AbilityId = 7,
                            AbilityName = "Khả năng truyền đạt",
                            Color = "#5db1bf"
                        },
                        new
                        {
                            AbilityId = 8,
                            AbilityName = "Khả năng thấu hiểu",
                            Color = "#662d9a"
                        },
                        new
                        {
                            AbilityId = 9,
                            AbilityName = "Có tính mềm dẻo, linh hoạt",
                            Color = "#2a9034"
                        },
                        new
                        {
                            AbilityId = 10,
                            AbilityName = "Khả năng nắm bắt tình huống",
                            Color = "#efaac3"
                        },
                        new
                        {
                            AbilityId = 11,
                            AbilityName = "Có tính kỷ luật",
                            Color = "#a33972"
                        },
                        new
                        {
                            AbilityId = 12,
                            AbilityName = "Khả năng chịu được áp lực",
                            Color = "#7291b6"
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int>("CourseCurrentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GuardianId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "06b12f97-bb16-434a-9982-e3d3dc1c5145",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1bc36d0c-394b-48a4-a59c-b2e63d72ad1a",
                            CourseCurrentId = 0,
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = true,
                            FullName = "TeamNET",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEFw/64Vv/eXtapxSkcIRhhrrxbcY1cFP7SdVYKpWZGsM6RjsxWdaGvnt0B6q7iMrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0c56ef80-b7df-4cac-82c0-a86d11240124",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@gmail.com"
                        },
                        new
                        {
                            Id = "16a69b03-3b90-49a2-9cac-4b940c91514c",
                            AccessFailedCount = 0,
                            AvatarName = "teacher.png",
                            ConcurrencyStamp = "61cb6af8-2933-438c-8892-cf67e388240f",
                            CourseCurrentId = 2,
                            Email = "teacher1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Teacher1",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER1@GMAIL.COM",
                            NormalizedUserName = "TEACHER1@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOy/N9F73EV7m6f89GMYjst1XF+ZD1UjuZVmoIaVFWsL4Y0oEP3u0bPKFUL2czXwTA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e02d225-f5a5-4d91-86c0-ab5a5ec7ee1e",
                            TwoFactorEnabled = false,
                            UserName = "teacher1@gmail.com"
                        },
                        new
                        {
                            Id = "1efe96d9-6618-4269-a6e3-ae1e3d3eecc4",
                            AccessFailedCount = 0,
                            AvatarName = "teacher.png",
                            ConcurrencyStamp = "618f4d9d-f660-4e32-94de-fdb6a9725dce",
                            CourseCurrentId = 3,
                            Email = "teacher2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Teacher2",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER2@GMAIL.COM",
                            NormalizedUserName = "TEACHER2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOynqsJVSoGOJtRNZyHjosaFy7y7/+1XeL1IyYZaTFykH2/a0O4BJfBUYn9uXxRTbg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24f64573-8a92-4189-b30c-0e3c98c71254",
                            TwoFactorEnabled = false,
                            UserName = "teacher2@gmail.com"
                        },
                        new
                        {
                            Id = "2115c7e6-9aae-43cb-a406-d504578498ba",
                            AccessFailedCount = 0,
                            AvatarName = "doctor.jpg",
                            ConcurrencyStamp = "b67124ea-fa08-4e39-b6df-1338c5da4b2f",
                            CourseCurrentId = 2,
                            Email = "doctor1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Doctor1",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@GMAIL.COM",
                            NormalizedUserName = "DOCTOR1@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECla3qbJca/Oyy3LhCvn0bkl7D4UlQaKm4pNRc/8fnWgzfWtq5YhFslH7pkcpjJ2zA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82e77d10-907c-44e2-83de-30751cbe70a3",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@gmail.com"
                        },
                        new
                        {
                            Id = "29a908b8-3ac4-45ea-a8a1-1cf9946079c7",
                            AccessFailedCount = 0,
                            AvatarName = "doctor.jpg",
                            ConcurrencyStamp = "884be8ae-9ddf-44dc-8bcd-855df2b00839",
                            CourseCurrentId = 3,
                            Email = "doctor2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Doctor2",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@GMAIL.COM",
                            NormalizedUserName = "DOCTOR2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEN25Y72PK4QxNBXBcAgvwIahTmtNklsrLznB577M+yhfEE7t6L1mI1QNOcB7nSZcLg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "127b0098-372c-4c78-9e46-b6796461cae9",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@gmail.com"
                        },
                        new
                        {
                            Id = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8",
                            AccessFailedCount = 0,
                            AvatarName = "student.png",
                            ConcurrencyStamp = "711e6fb4-a4da-46aa-a478-98878eb8f005",
                            CourseCurrentId = 2,
                            Email = "student1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Student1",
                            GuardianId = "3dabf300-50ab-438b-baaa-f6890f2b260c",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@GMAIL.COM",
                            NormalizedUserName = "STUDENT1@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEG5P0yPIblhNX6b2eyZNbyUBcxvtWFM7e7ZXRi/sbDx6RunzVR0q6EDCYl35NPmVzg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3578db57-f17a-411d-aa5d-cb1d400f4003",
                            StudentCode = "ST00001",
                            TwoFactorEnabled = false,
                            UserName = "student1@gmail.com"
                        },
                        new
                        {
                            Id = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c",
                            AccessFailedCount = 0,
                            AvatarName = "student.png",
                            ConcurrencyStamp = "604990df-cd37-4e20-87d4-432b1a893d3e",
                            CourseCurrentId = 2,
                            Email = "student2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Student2",
                            GuardianId = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT2@GMAIL.COM",
                            NormalizedUserName = "STUDENT2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAYG6w8/oTNXENLivWIn5V5ZD+6qyN2qLwxNg/8+2Si7aDPlTHyoMvyXvDNC10DHGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c92906b6-4b9e-450f-a165-7f3bffa9cf9d",
                            StudentCode = "ST00002",
                            TwoFactorEnabled = false,
                            UserName = "student2@gmail.com"
                        },
                        new
                        {
                            Id = "3c592e96-f3ad-4e8b-9cbe-afb7ea745362",
                            AccessFailedCount = 0,
                            AvatarName = "student.png",
                            ConcurrencyStamp = "a8c627c5-19d1-424c-8f5e-5be64ba29b83",
                            CourseCurrentId = 3,
                            Email = "student3@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Student3",
                            GuardianId = "3dabf300-50ab-438b-baaa-f6890f2b260c",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT3@GMAIL.COM",
                            NormalizedUserName = "STUDENT3@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEATevlkCJa2tGoITeOmkKFBe1hICSR90OMjVcZ9sTo3ugMa5L7Cz83h18osiZEQ6UQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6089ac6a-76b1-4aaf-b022-4effb10a5a44",
                            StudentCode = "ST00003",
                            TwoFactorEnabled = false,
                            UserName = "student3@gmail.com"
                        },
                        new
                        {
                            Id = "3dabf300-50ab-438b-baaa-f6890f2b260c",
                            AccessFailedCount = 0,
                            AvatarName = "guardian.png",
                            ConcurrencyStamp = "54cb7c5c-012c-4289-8085-2c48dcd113b3",
                            CourseCurrentId = 0,
                            Email = "guardian1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Guardian1",
                            LockoutEnabled = false,
                            NormalizedEmail = "GUARDIAN1@GMAIL.COM",
                            NormalizedUserName = "GUARDIAN1@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENK1Xb0u6aQHRSrXaqtl8NnLFU5UIphm2HnBCNZvE6X72en3B3oxeJ8BftjQizpb5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c8ec0ce7-c9e7-46d5-b2f5-db167e4ea6d2",
                            TwoFactorEnabled = false,
                            UserName = "guardian1@gmail.com"
                        },
                        new
                        {
                            Id = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5",
                            AccessFailedCount = 0,
                            AvatarName = "guardian.png",
                            ConcurrencyStamp = "a3988807-7363-444d-b37d-b4ea09d2915d",
                            CourseCurrentId = 0,
                            Email = "guardian2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Guardian2",
                            LockoutEnabled = false,
                            NormalizedEmail = "GUARDIAN2@GMAIL.COM",
                            NormalizedUserName = "GUARDIAN2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELjEf4sv/odyjMM6hoX5SRm+o42CWWE8pHmPLarO0EuxwWC8ooffzH37LDgqp643EA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "adea5e41-a3d7-4fe9-997d-f71d64de3808",
                            TwoFactorEnabled = false,
                            UserName = "guardian2@gmail.com"
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EventContentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RealTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("CommentId");

                    b.HasIndex("EventContentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            EventContentId = 1,
                            RealTime = new DateTime(2020, 2, 12, 13, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 1",
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            CommentId = 2,
                            EventContentId = 1,
                            RealTime = new DateTime(2020, 2, 12, 15, 10, 20, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 1",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 3,
                            EventContentId = 1,
                            RealTime = new DateTime(2020, 2, 12, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Tính tự lập #Khả năng lập kế hoạch #Có tính kỷ luật - DoctorComentEvent 1",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 4,
                            EventContentId = 1,
                            RealTime = new DateTime(2020, 2, 12, 20, 15, 55, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 1",
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            CommentId = 5,
                            EventContentId = 2,
                            RealTime = new DateTime(2020, 2, 15, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 2",
                            UserId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c"
                        },
                        new
                        {
                            CommentId = 6,
                            EventContentId = 2,
                            RealTime = new DateTime(2020, 2, 15, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 2",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 7,
                            EventContentId = 2,
                            RealTime = new DateTime(2020, 2, 15, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Khả năng làm việc - DoctorComentEvent 2",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 8,
                            EventContentId = 2,
                            RealTime = new DateTime(2020, 2, 15, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 2",
                            UserId = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5"
                        },
                        new
                        {
                            CommentId = 9,
                            EventContentId = 3,
                            RealTime = new DateTime(2020, 5, 20, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 3",
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            CommentId = 10,
                            EventContentId = 3,
                            RealTime = new DateTime(2020, 5, 20, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 3",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 11,
                            EventContentId = 3,
                            RealTime = new DateTime(2020, 5, 20, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Khả năng làm việc - DoctorComentEvent 3",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 12,
                            EventContentId = 3,
                            RealTime = new DateTime(2020, 5, 20, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 3",
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            CommentId = 13,
                            EventContentId = 4,
                            RealTime = new DateTime(2020, 6, 25, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 4",
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            CommentId = 14,
                            EventContentId = 4,
                            RealTime = new DateTime(2020, 6, 25, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 4",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 15,
                            EventContentId = 4,
                            RealTime = new DateTime(2020, 6, 25, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Khả năng làm việc - DoctorComentEvent 4",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 16,
                            EventContentId = 4,
                            RealTime = new DateTime(2020, 6, 25, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 4",
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            CommentId = 17,
                            EventContentId = 5,
                            RealTime = new DateTime(2020, 7, 12, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 5",
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            CommentId = 18,
                            EventContentId = 5,
                            RealTime = new DateTime(2020, 7, 12, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 5",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 19,
                            EventContentId = 5,
                            RealTime = new DateTime(2020, 7, 12, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Khả năng lập kế hoạch - DoctorComentEvent 5",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 20,
                            EventContentId = 5,
                            RealTime = new DateTime(2020, 7, 12, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 5",
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            CommentId = 21,
                            EventContentId = 6,
                            RealTime = new DateTime(2020, 7, 20, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 6",
                            UserId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c"
                        },
                        new
                        {
                            CommentId = 22,
                            EventContentId = 6,
                            RealTime = new DateTime(2020, 7, 20, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 6",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 23,
                            EventContentId = 6,
                            RealTime = new DateTime(2020, 7, 20, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Có tính mềm dẻo, linh hoạt - DoctorComentEvent 6",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 24,
                            EventContentId = 6,
                            RealTime = new DateTime(2020, 7, 20, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 6",
                            UserId = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5"
                        },
                        new
                        {
                            CommentId = 25,
                            EventContentId = 7,
                            RealTime = new DateTime(2021, 1, 25, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 7",
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            CommentId = 26,
                            EventContentId = 7,
                            RealTime = new DateTime(2021, 1, 25, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 7",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 27,
                            EventContentId = 7,
                            RealTime = new DateTime(2021, 1, 25, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Khả năng thực hành - Có tính mềm dẻo, linh hoạt - DoctorComentEvent 7",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 28,
                            EventContentId = 7,
                            RealTime = new DateTime(2020, 7, 25, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 7",
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            CommentId = 29,
                            EventContentId = 8,
                            RealTime = new DateTime(2021, 2, 2, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 8",
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            CommentId = 30,
                            EventContentId = 8,
                            RealTime = new DateTime(2021, 2, 2, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 8",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 31,
                            EventContentId = 8,
                            RealTime = new DateTime(2021, 2, 2, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Khả năng chịu được áp lực - DoctorComentEvent 8",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 32,
                            EventContentId = 8,
                            RealTime = new DateTime(2020, 2, 2, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 8",
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            CommentId = 33,
                            EventContentId = 9,
                            RealTime = new DateTime(2021, 2, 10, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 9",
                            UserId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c"
                        },
                        new
                        {
                            CommentId = 34,
                            EventContentId = 9,
                            RealTime = new DateTime(2021, 2, 10, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 9",
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CommentId = 35,
                            EventContentId = 9,
                            RealTime = new DateTime(2021, 2, 10, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Tính tự lập - DoctorComentEvent 9",
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            CommentId = 36,
                            EventContentId = 9,
                            RealTime = new DateTime(2021, 2, 10, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 9",
                            UserId = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5"
                        },
                        new
                        {
                            CommentId = 37,
                            EventContentId = 10,
                            RealTime = new DateTime(2021, 3, 15, 14, 15, 25, 0, DateTimeKind.Unspecified),
                            Text = "StudentComentEvent 10",
                            UserId = "3c592e96-f3ad-4e8b-9cbe-afb7ea745362"
                        },
                        new
                        {
                            CommentId = 38,
                            EventContentId = 10,
                            RealTime = new DateTime(2021, 3, 15, 16, 20, 50, 0, DateTimeKind.Unspecified),
                            Text = "TeacherComentEvent 10",
                            UserId = "1efe96d9-6618-4269-a6e3-ae1e3d3eecc4"
                        },
                        new
                        {
                            CommentId = 39,
                            EventContentId = 10,
                            RealTime = new DateTime(2021, 3, 15, 17, 30, 40, 0, DateTimeKind.Unspecified),
                            Text = "#Khả năng giải quyết vấn đề #Khả năng sáng tạo - DoctorComentEvent 10",
                            UserId = "29a908b8-3ac4-45ea-a8a1-1cf9946079c7"
                        },
                        new
                        {
                            CommentId = 40,
                            EventContentId = 10,
                            RealTime = new DateTime(2020, 3, 15, 19, 5, 25, 0, DateTimeKind.Unspecified),
                            Text = "GuardianComentEvent 10",
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Class 1"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Class 2"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Class 3"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Class 4"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Class 5"
                        },
                        new
                        {
                            CourseId = 6,
                            CourseName = "Class 6"
                        },
                        new
                        {
                            CourseId = 7,
                            CourseName = "Class 7"
                        },
                        new
                        {
                            CourseId = 8,
                            CourseName = "Class 8"
                        },
                        new
                        {
                            CourseId = 9,
                            CourseName = "Class 9"
                        },
                        new
                        {
                            CourseId = 10,
                            CourseName = "Class 10"
                        },
                        new
                        {
                            CourseId = 11,
                            CourseName = "Class 11"
                        },
                        new
                        {
                            CourseId = 12,
                            CourseName = "Class 12"
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EventName = "Bóng đá",
                            Icon = "fa fa-futbol-o"
                        },
                        new
                        {
                            EventId = 2,
                            EventName = "Hát",
                            Icon = "las la-microphone-alt"
                        },
                        new
                        {
                            EventId = 3,
                            EventName = "Bóng chuyền",
                            Icon = "las la-volleyball-ball"
                        },
                        new
                        {
                            EventId = 4,
                            EventName = "Bóng rổ",
                            Icon = "las la-basketball-ball"
                        },
                        new
                        {
                            EventId = 5,
                            EventName = "Sách",
                            Icon = "las la-book-reader"
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.EventContent", b =>
                {
                    b.Property<int>("EventContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ActionAbility")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CommunityAbility")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CourseCurrentId")
                        .HasColumnType("integer");

                    b.Property<string>("DemonstratedAbility")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("SelfDevelopment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.Property<string>("ThinkingAbility")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("EventContentId");

                    b.HasIndex("CourseCurrentId");

                    b.HasIndex("EventId");

                    b.HasIndex("StudentId");

                    b.ToTable("EventContents");

                    b.HasData(
                        new
                        {
                            EventContentId = 1,
                            ActionAbility = "Answer 12",
                            CommunityAbility = "Answer 11",
                            CourseCurrentId = 1,
                            DemonstratedAbility = "Answer 13",
                            EventId = 1,
                            SelfDevelopment = "Answer 14",
                            StatusId = 3,
                            StudentId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8",
                            ThinkingAbility = "Answer 15"
                        },
                        new
                        {
                            EventContentId = 2,
                            ActionAbility = "Answer 22",
                            CommunityAbility = "Answer 21",
                            CourseCurrentId = 1,
                            DemonstratedAbility = "Answer 23",
                            EventId = 3,
                            SelfDevelopment = "Answer 24",
                            StatusId = 3,
                            StudentId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c",
                            ThinkingAbility = "Answer 25"
                        },
                        new
                        {
                            EventContentId = 3,
                            ActionAbility = "Answer 112",
                            CommunityAbility = "Answer 111",
                            CourseCurrentId = 1,
                            DemonstratedAbility = "Answer 113",
                            EventId = 4,
                            SelfDevelopment = "Answer 114",
                            StatusId = 3,
                            StudentId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8",
                            ThinkingAbility = "Answer 115"
                        },
                        new
                        {
                            EventContentId = 4,
                            ActionAbility = "Answer 1112",
                            CommunityAbility = "Answer 1111",
                            CourseCurrentId = 1,
                            DemonstratedAbility = "Answer 1113",
                            EventId = 4,
                            SelfDevelopment = "Answer 1114",
                            StatusId = 3,
                            StudentId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8",
                            ThinkingAbility = "Answer 1115"
                        },
                        new
                        {
                            EventContentId = 5,
                            ActionAbility = "Answer 11112",
                            CommunityAbility = "Answer 11111",
                            CourseCurrentId = 1,
                            DemonstratedAbility = "Answer 11113",
                            EventId = 5,
                            SelfDevelopment = "Answer 11114",
                            StatusId = 3,
                            StudentId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8",
                            ThinkingAbility = "Answer 11115"
                        },
                        new
                        {
                            EventContentId = 6,
                            ActionAbility = "Answer 222",
                            CommunityAbility = "Answer 221",
                            CourseCurrentId = 1,
                            DemonstratedAbility = "Answer 223",
                            EventId = 2,
                            SelfDevelopment = "Answer 224",
                            StatusId = 3,
                            StudentId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c",
                            ThinkingAbility = "Answer 225"
                        },
                        new
                        {
                            EventContentId = 7,
                            ActionAbility = "Answer 111112",
                            CommunityAbility = "Answer 111111",
                            CourseCurrentId = 2,
                            DemonstratedAbility = "Answer 111113",
                            EventId = 2,
                            SelfDevelopment = "Answer 111114",
                            StatusId = 1,
                            StudentId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8",
                            ThinkingAbility = "Answer 111115"
                        },
                        new
                        {
                            EventContentId = 8,
                            ActionAbility = "Answer 1111112",
                            CommunityAbility = "Answer 1111111",
                            CourseCurrentId = 2,
                            DemonstratedAbility = "Answer 1111113",
                            EventId = 2,
                            SelfDevelopment = "Answer 1111114",
                            StatusId = 1,
                            StudentId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8",
                            ThinkingAbility = "Answer 1111115"
                        },
                        new
                        {
                            EventContentId = 9,
                            ActionAbility = "Answer 2222",
                            CommunityAbility = "Answer 2221",
                            CourseCurrentId = 2,
                            DemonstratedAbility = "Answer 2223",
                            EventId = 5,
                            SelfDevelopment = "Answer 2224",
                            StatusId = 1,
                            StudentId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c",
                            ThinkingAbility = "Answer 2225"
                        },
                        new
                        {
                            EventContentId = 10,
                            ActionAbility = "Answer 32",
                            CommunityAbility = "Answer 31",
                            CourseCurrentId = 3,
                            DemonstratedAbility = "Answer 33",
                            EventId = 3,
                            SelfDevelopment = "Answer 34",
                            StatusId = 1,
                            StudentId = "3c592e96-f3ad-4e8b-9cbe-afb7ea745362",
                            ThinkingAbility = "Answer 35"
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.EventContentAbility", b =>
                {
                    b.Property<int>("EventContentId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.HasKey("EventContentId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("EventContentAbilities");

                    b.HasData(
                        new
                        {
                            EventContentId = 1,
                            AbilityId = 1
                        },
                        new
                        {
                            EventContentId = 1,
                            AbilityId = 5
                        },
                        new
                        {
                            EventContentId = 1,
                            AbilityId = 11
                        },
                        new
                        {
                            EventContentId = 2,
                            AbilityId = 2
                        },
                        new
                        {
                            EventContentId = 3,
                            AbilityId = 2
                        },
                        new
                        {
                            EventContentId = 4,
                            AbilityId = 2
                        },
                        new
                        {
                            EventContentId = 5,
                            AbilityId = 5
                        },
                        new
                        {
                            EventContentId = 6,
                            AbilityId = 9
                        },
                        new
                        {
                            EventContentId = 7,
                            AbilityId = 3
                        },
                        new
                        {
                            EventContentId = 8,
                            AbilityId = 12
                        },
                        new
                        {
                            EventContentId = 9,
                            AbilityId = 1
                        },
                        new
                        {
                            EventContentId = 10,
                            AbilityId = 4
                        },
                        new
                        {
                            EventContentId = 10,
                            AbilityId = 6
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.NotificationEventContent", b =>
                {
                    b.Property<int>("NotificationEventContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EventContentId")
                        .HasColumnType("integer");

                    b.Property<int>("Notification")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("NotificationEventContentId");

                    b.HasIndex("EventContentId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationEventContents");

                    b.HasData(
                        new
                        {
                            NotificationEventContentId = 1,
                            EventContentId = 1,
                            Notification = 0,
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            NotificationEventContentId = 2,
                            EventContentId = 1,
                            Notification = 0,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 3,
                            EventContentId = 1,
                            Notification = 0,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 4,
                            EventContentId = 1,
                            Notification = 0,
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            NotificationEventContentId = 5,
                            EventContentId = 2,
                            Notification = 0,
                            UserId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c"
                        },
                        new
                        {
                            NotificationEventContentId = 6,
                            EventContentId = 2,
                            Notification = 0,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 7,
                            EventContentId = 2,
                            Notification = 0,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 8,
                            EventContentId = 2,
                            Notification = 0,
                            UserId = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5"
                        },
                        new
                        {
                            NotificationEventContentId = 9,
                            EventContentId = 3,
                            Notification = 0,
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            NotificationEventContentId = 10,
                            EventContentId = 3,
                            Notification = 0,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 11,
                            EventContentId = 3,
                            Notification = 0,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 12,
                            EventContentId = 3,
                            Notification = 0,
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            NotificationEventContentId = 13,
                            EventContentId = 4,
                            Notification = 0,
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            NotificationEventContentId = 14,
                            EventContentId = 4,
                            Notification = 0,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 15,
                            EventContentId = 4,
                            Notification = 0,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 16,
                            EventContentId = 4,
                            Notification = 0,
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            NotificationEventContentId = 17,
                            EventContentId = 5,
                            Notification = 0,
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            NotificationEventContentId = 18,
                            EventContentId = 5,
                            Notification = 0,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 19,
                            EventContentId = 5,
                            Notification = 0,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 20,
                            EventContentId = 5,
                            Notification = 0,
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            NotificationEventContentId = 21,
                            EventContentId = 6,
                            Notification = 0,
                            UserId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c"
                        },
                        new
                        {
                            NotificationEventContentId = 22,
                            EventContentId = 6,
                            Notification = 0,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 23,
                            EventContentId = 6,
                            Notification = 0,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 24,
                            EventContentId = 6,
                            Notification = 0,
                            UserId = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5"
                        },
                        new
                        {
                            NotificationEventContentId = 25,
                            EventContentId = 7,
                            Notification = 0,
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            NotificationEventContentId = 26,
                            EventContentId = 7,
                            Notification = 0,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 27,
                            EventContentId = 7,
                            Notification = 0,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 28,
                            EventContentId = 7,
                            Notification = 0,
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            NotificationEventContentId = 29,
                            EventContentId = 8,
                            Notification = 0,
                            UserId = "2f3baf7f-a5b4-4627-abcb-0e42e2fb33a8"
                        },
                        new
                        {
                            NotificationEventContentId = 30,
                            EventContentId = 8,
                            Notification = 2,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 31,
                            EventContentId = 8,
                            Notification = 0,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 32,
                            EventContentId = 8,
                            Notification = 3,
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        },
                        new
                        {
                            NotificationEventContentId = 33,
                            EventContentId = 9,
                            Notification = 1,
                            UserId = "2f67c183-6ebf-4920-9cca-7d1a7a2b173c"
                        },
                        new
                        {
                            NotificationEventContentId = 34,
                            EventContentId = 9,
                            Notification = 2,
                            UserId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            NotificationEventContentId = 35,
                            EventContentId = 9,
                            Notification = 1,
                            UserId = "2115c7e6-9aae-43cb-a406-d504578498ba"
                        },
                        new
                        {
                            NotificationEventContentId = 36,
                            EventContentId = 9,
                            Notification = 0,
                            UserId = "560b9a81-71e6-4987-a6c2-ecf72ecd36b5"
                        },
                        new
                        {
                            NotificationEventContentId = 37,
                            EventContentId = 10,
                            Notification = 3,
                            UserId = "3c592e96-f3ad-4e8b-9cbe-afb7ea745362"
                        },
                        new
                        {
                            NotificationEventContentId = 38,
                            EventContentId = 10,
                            Notification = 2,
                            UserId = "1efe96d9-6618-4269-a6e3-ae1e3d3eecc4"
                        },
                        new
                        {
                            NotificationEventContentId = 39,
                            EventContentId = 10,
                            Notification = 0,
                            UserId = "29a908b8-3ac4-45ea-a8a1-1cf9946079c7"
                        },
                        new
                        {
                            NotificationEventContentId = 40,
                            EventContentId = 10,
                            Notification = 2,
                            UserId = "3dabf300-50ab-438b-baaa-f6890f2b260c"
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.UserCourseDetail", b =>
                {
                    b.Property<int>("CourseCurrentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.HasKey("CourseCurrentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("TeacherId");

                    b.ToTable("UserCourseDetails");

                    b.HasData(
                        new
                        {
                            CourseCurrentId = 1,
                            CourseId = 1,
                            DoctorId = "2115c7e6-9aae-43cb-a406-d504578498ba",
                            TeacherId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CourseCurrentId = 2,
                            CourseId = 2,
                            DoctorId = "2115c7e6-9aae-43cb-a406-d504578498ba",
                            TeacherId = "16a69b03-3b90-49a2-9cac-4b940c91514c"
                        },
                        new
                        {
                            CourseCurrentId = 3,
                            CourseId = 1,
                            DoctorId = "29a908b8-3ac4-45ea-a8a1-1cf9946079c7",
                            TeacherId = "1efe96d9-6618-4269-a6e3-ae1e3d3eecc4"
                        });
                });

            modelBuilder.Entity("TeamNET.Models.Entity.Wiki", b =>
                {
                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TableId", "StatusId");

                    b.ToTable("Wikis");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            StatusId = 1,
                            IsDeleted = false,
                            StatusName = "Đang xác nhận",
                            TableName = "EventContent"
                        },
                        new
                        {
                            TableId = 1,
                            StatusId = 2,
                            IsDeleted = false,
                            StatusName = "Xác nhận",
                            TableName = "EventContent"
                        },
                        new
                        {
                            TableId = 1,
                            StatusId = 3,
                            IsDeleted = false,
                            StatusName = "Hoàn thành",
                            TableName = "EventContent"
                        },
                        new
                        {
                            TableId = 1,
                            StatusId = 4,
                            IsDeleted = false,
                            StatusName = "Đã xóa",
                            TableName = "EventContent"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamNET.Models.Entity.Comment", b =>
                {
                    b.HasOne("TeamNET.Models.Entity.EventContent", "EventContent")
                        .WithMany("Comments")
                        .HasForeignKey("EventContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("EventContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamNET.Models.Entity.EventContent", b =>
                {
                    b.HasOne("TeamNET.Models.Entity.UserCourseDetail", "UserCourseDetalis")
                        .WithMany()
                        .HasForeignKey("CourseCurrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamNET.Models.Entity.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", "ApplicationUser")
                        .WithMany("EventContents")
                        .HasForeignKey("StudentId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Event");

                    b.Navigation("UserCourseDetalis");
                });

            modelBuilder.Entity("TeamNET.Models.Entity.EventContentAbility", b =>
                {
                    b.HasOne("TeamNET.Models.Entity.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamNET.Models.Entity.EventContent", "EventContent")
                        .WithMany("EventContentAbilities")
                        .HasForeignKey("EventContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("EventContent");
                });

            modelBuilder.Entity("TeamNET.Models.Entity.NotificationEventContent", b =>
                {
                    b.HasOne("TeamNET.Models.Entity.EventContent", "EventContent")
                        .WithMany("NotificationEventContents")
                        .HasForeignKey("EventContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", "UserNotification")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("EventContent");

                    b.Navigation("UserNotification");
                });

            modelBuilder.Entity("TeamNET.Models.Entity.UserCourseDetail", b =>
                {
                    b.HasOne("TeamNET.Models.Entity.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("TeamNET.Models.Entity.ApplicationUser", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Course");

                    b.Navigation("Doctor");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeamNET.Models.Entity.ApplicationUser", b =>
                {
                    b.Navigation("EventContents");
                });

            modelBuilder.Entity("TeamNET.Models.Entity.EventContent", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EventContentAbilities");

                    b.Navigation("NotificationEventContents");
                });
#pragma warning restore 612, 618
        }
    }
}
